RA-09
LostTales/RecipeApp pull request #7
Opened 2024-01-23 21:52 UTC by LostTales

2024-01-24 12:16 UTC, ievetrovdev requested changes
Заголовок категорий tvTitleOfTheCategorySection и списка рецептов отличается по отступам от макета. кроме того там можно обойтись от констрейнтов сверху. и справа убрать захардкоженное значение. Цель добиться того, чтобы контейнер был адаптивен, но при длинном тексте справа был такой же отступ, как и слева

2024-01-24 12:16 UTC, ievetrovdev commented on app/src/main/java/ru/shypitsa/recipeapp/CategoriesListFragment.kt
> +        fragmentManager?.popBackStack()
обрати внимание
`'getter for fragmentManager: FragmentManager?' is deprecated. Deprecated in Java`

2024-01-24 12:16 UTC, ievetrovdev commented on app/src/main/java/ru/shypitsa/recipeapp/CategoriesListFragment.kt
> +        fragmentManager?.popBackStack()
для осуществления перехода из фрагменте попробуй использовать parentFragmentManager

2024-01-26 12:37 UTC, ievetrov requested changes
И то, о чем упомянул в ЛС. Подстановку item_image_in_the_categories_section реализовать в адаптере списка категорий

2024-01-26 12:37 UTC, ievetrov commented on app/src/main/java/ru/shypitsa/recipeapp/CategoriesListFragment.kt
> +        parentFragmentManager.popBackStack()
`popBackStack()` удаляет верхний фрагмент из стека фрагментов. В связи с этим следующий фрагмент на который мы переходим становится первым. Это немного ломает пользовательский опыт, тк при переходе на экран со списком рецептов – не работает кнопка "Назад", потому, что в стеке нет предыдущего фрагмента.

2024-01-26 12:37 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> -        android:layout_height="224dp">
Высоту изображения оставляем с точными значениями. Все остальное будет адаптивно

2024-01-26 12:37 UTC, ievetrov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="tv_title_layout_margin_dim">16dp</dimen>
Комментарий ко всему файлу с размерами

Повторять одни и те же значения с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-01-27 11:19 UTC, ievetrov approved these changes

2024-01-27 11:19 UTC, ievetrov commented on app/src/main/java/ru/shypitsa/recipeapp/CategoriesListAdapter.kt
> +        holder.contentDescription.contentDescription = dataSet[position].title
Корректно, только скринридер и так прочтет этот заголовок. Тут корректнее будет добавить чуть более развернутое описание, например, "Изображение для карточки категории название_категории"

2024-01-27 18:49 UTC, merged